install.packages("tree")
install.packages("C50")
library(C50)
library(tree)
tree1<-read.csv("F://assignment 2/CompanyData.csv")
tree1_yes<-tree1[tree1$US=="Yes",]
tree1_no <-tree1[tree1$US=="No",]
tree_train<-rbind(tree1_yes[1:350,],tree1_no[1:350,])
tree_test<-rbind(tree1_yes[351:400,],tree1_no[351:400,])
treec50_train<-C5.0(tree_train[,-10],tree_train$US)
windows()
plot(treec50_train)
pred_train<-predict(treec50_train,tree_train)
mean(tree_train$US==pred_train)
install.packages("caret")
library(caret)
confusionMatrix(pred_train,tree_train$US)
pred_test<-predict(treec50_train,newdata=tree_test)
mean(pred_test==tree_test$US)
confusionMatrix(pred_test,tree_test$US)
